import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar'; // Corrected import path
import Footer from '@/components/Footer'; // Corrected import path
import {ThemeProvider} from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from '@/context/AuthContext'; // Import AuthProvider
import QueryProvider from '@/context/QueryProvider'; // Import QueryProvider


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'AffiliateLink Hub',
  description: 'Generated by Firebase Studio',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <AuthProvider> {/* Wrap with AuthProvider */}
            <QueryProvider> {/* Wrap with QueryProvider */}
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                    <Navbar />
                    <main className="container mx-auto p-4 pt-20">
                      {children}
                    </main>
                    <Footer />
                    <Toaster />
                </ThemeProvider>
             </QueryProvider> {/* Close QueryProvider */}
          </AuthProvider> {/* Close AuthProvider */}
        </body>
    </html>
  );
}
